# Generated by Django 4.2 on 2023-06-07 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TimeField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('autor_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('titulo_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_noticias.noticia')),
            ],
        ),
    ]
