# Generated by Django 4.2 on 2023-06-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto_comentario',
            field=models.TextField(),
        ),
    ]
