# Generated by Django 4.2 on 2023-06-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0003_alter_comentario_texto_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='autor_comentario',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='data_comentario',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='texto_comentario',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='titulo_comentario',
            new_name='titulo',
        ),
    ]
