# Generated by Django 4.2 on 2023-06-09 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0004_rename_autor_comentario_comentario_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='data_publicacao',
            new_name='data',
        ),
    ]
